name: Indent

on:
  push:
    branches: 
      - master
      - experimental_merge_vector
  pull_request:
    branches: 
      - master
      - experimental_merge_vector

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        exclude: ''
        extensions: 'h,cc'
        clangFormatVersion: 16
        inplace: true
    - run: |
        git diff
        git diff-files --quiet || exit $?
